### ISSUE TITLE
[1.0.0-beta.68] OAuth2 - client_credentials should not return refresh token?

### ISSUE THREAD

**Issue by alejandro-miguez** [bondy-io/bondy#19]
At Latam LoJack we are upgrading to the latest version of bondy **1.0.0-beta.68** and We noticed that the `refresh_token` is not present when a issuing a new token for **grant_type**=`client_credentials`.
Due to the "BackOffice" webapps are using and implementing the oauth2 flow, we need the refresh token. Below an issued token without the `refresh_token` attribute:
- **Request**:
```bash
curl --location --request POST 'https://lj-test02-v2.api.strix.com.ar/oauth/token' \
--header 'Authorization: Basic dFJ1QmFhWVBwWVRDWmprQTI2Rjgzak5KOTRoNHZkcGY6d0JRTTRwZlNUNzliMjVtTkYyTmJoZEtFZ2R5amdlNEM=' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials'
```
- **Response**:
```json
{
    "access_token": "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJjb20ubWFnZW50YS50ZXN0IiwiZXhwIjo5MDAsImdyb3VwcyI6WyJhZG1pbiIsImFwaV9jbGllbnRzIl0sImlhdCI6MTY3MjA5NjMyNCwiaWQiOjY4MDY1NTQ1MzkyNjQ4NTksImlzcyI6InRydWJhYXlwcHl0Y3pqa2EyNmY4M2puajk0aDR2ZHBmIiwia2lkIjoiNzcyNzExODEiLCJtZXRhIjp7ImRlc2NyaXB0aW9uIjoiU3RyaXggRmxlZXQgYWRtaW4ifSwic3ViIjoidHJ1YmFheXBweXRjemprYTI2Zjgzam5qOTRoNHZkcGYifQ.bYhLZnlH6faQRCqHGnz5bgFgfI8n5tAc0-mfnSowNa3ceGENaiHQHxE2ERP1Ved7nSWXnuoqMzA_kfJMuNnzEA",
    "expires_in": 900,
    "scope": "admin,api_clients",
    "token_type": "bearer"
}
```

The change was applied with the following commit: https://github.com/bondy-io/bondy/commit/0d2e6729646bea8a499e1a81bdacf2127c18c139 chanding a private function in module **bondy_oauth2**:
```erlang
%% @private
supports_refresh_token(client_credentials) -> false;
supports_refresh_token(application_code) -> true;
supports_refresh_token(password) -> true;
supports_refresh_token(Grant) -> error({oauth2_unsupported_grant_type, Grant}).
```
Is possible to support it? maybe using some configurable feature?

**Comment by aramallo** [comment]
Hi @alejandro-miguez , thanks for this.

The client credentials flow SHOULD not return a refresh token as per the [spec](https://tools.ietf.org/html/rfc6749#section-4.4.3).

This makes sense as the refresh token exists to obtain a new token on behalf of the end user without asking it to authenticate again. But the Client (app) should always authenticate, in which case a refresh token does not make sense and it should simple obtain a new token.
