### ISSUE TITLE
Cannot enable or disable users in realm

### ISSUE THREAD

**Issue by Jopie01** [bondy-io/bondy#25]
I get an error when I want to enable or disable a user. Using `wick` from the documentation
```
/wick --url ws://localhost:18080/ws \
--realm com.leapsight.bondy \
call bondy.realm.security.disable "com.leapsight.test_creation_1"
```
I get
```
FATA[0000] got errors:
- calling remote procedure 'bondy.user.disable': bondy.error.function_clause: : code=function_clause, description=, message= 
```
Using `curl`
```
curl -X "POST" "http://localhost:18081/services/call"
  -H 'Content-Type: application/json; charset=utf-8'
  -H 'Accept: application/json; charset=utf-8'
  -d $'{
    "procedure": "bondy.user.enable",
    "options": {},
    "args": [
      "com.leapsight.test",
      "peer1"
    ],
    "kwargs": {}
  }'
```
I get 
```
{"args":[""],"details":{},"error_uri":"bondy.error.function_clause","kwargs":{"code":"function_clause","description":"","message":""}}
```
Digging / tracing through the code and trying to debug, the error comes from:
https://github.com/bondy-io/bondy/blob/e72460e094cd0d897e74a5c2864c6eaa3cd7a213/apps/bondy/src/bondy_rbac_user.erl#L860-L864

The problem is that the User send is a Binary and it seems that the function is expecting something different. Removing the type check will fix the problem and I can enable and disable an user. But I don't think that's the right thing to do right? I suppose it should be fixed in https://github.com/bondy-io/bondy/blob/e72460e094cd0d897e74a5c2864c6eaa3cd7a213/apps/bondy/src/bondy_rbac_user_wamp_api.erl#L96

All the above happens for both enable and disable an user.

**Comment by aramallo** [comment]
Thanks @Jopie01 I’ll take a look tomorrow and get back to you.

**Comment by aramallo** [comment]
@Jopie01 Just made a commit to `develop` fixing this issue and improving some other validations.

If you do:
```shell
wick --url ws://localhost:18080/ws --realm com.leapsight.test \
call bondy.user.enable "app1"
```
_No return_

Then:

```shell
wick --url ws://localhost:18080/ws --realm com.leapsight.test \
call bondy.user.is_enabled "app1"
```
should return 
```json
[ 
   false
]
```

**Comment by Jopie01** [comment]
@aramallo Thanks! Did a pull and now it works perfectly!

Also using `curl` is working with
```
curl -X "POST" "http://localhost:18081/services/call"
  -H 'Content-Type: application/json; charset=utf-8'
  -H 'Accept: application/json; charset=utf-8'
  -d $'{
    "procedure": "bondy.user.enable",
    "options": {},
    "args": [
      "com.leapsight.test",
      "peer1"
    ],
    "kwargs": {}
  }'
```
And replacing `bondy.user.enable` with `bondy.user.disable` is also working.
