### ISSUE TITLE
make release fails, because of "${REBAR} as ${REBAR3_PROFILE}" (At least one task must be specified when using `as`)

### ISSUE THREAD

**Issue by JensUngerer** [bondy-io/bondy#27]
when trying to compile with ``make relase``,
the build fails:

[make-release-err-out.log](https://github.com/bondy-io/bondy/files/14960835/make-release-err-out.log)
[make-release-std-out.log](https://github.com/bondy-io/bondy/files/14960836/make-release-std-out.log)

**Comment by aramallo** [comment]
Thanks @JensUngerer there is a missing command in the make target, fixing it now.
